config {
  type: "view",
  schema: "pontuacao",
  name: "op_pontuacao_join_1",
  description: "puxando colunas da tabela de usuarios",
  tags: ["join", "pontuacao", "usuarios"]
}


SELECT 

col.*,
usr.Email,
usr.Id_Zap,
usr.Perfil,
usr.Categoria,

FROM ${ref("raw_statements_tratado")} as col

LEFT JOIN ${ref("raw_users_tratado")} as usr 


on col.Id_Usuario = usr.Id_Usuario

where col.Status = "Disponível"

