config {
  type: "table",
  schema: "bi_dashboard",
  name: "bi_statements",
  description: "tabela final de pontuacao",
  tags: ["bi", "statements","pontuacao"]
}


SELECT *,
 CASE WHEN Tipo = "Missão" 
       AND FORMAT_DATE('%Y-%m', DATE(Data)) = MIN(FORMAT_DATE('%Y-%m', DATE(Data))) OVER (PARTITION BY Email) 
  THEN 'sim'
  WHEN Tipo = "Missão" 
  THEN 'não'
  ELSE NULL END AS mes_prim_missao
FROM ${ref("op_pontuacao_join_1")}